// src/pages/Home.js
import React from "react";
import { useNavigate } from "react-router-dom";
import { Container, Row, Col, Card, Button } from "react-bootstrap";
import MainLayout from "../components/MainLayout";

export default function Home() {
  const navigate = useNavigate();

  return (
    <MainLayout>
      <Container className="my-5 text-center">
        <h1>Welcome to LearnHub</h1>
        <p className="mb-5">
          Generate comprehensive learning paths for any topic with AI-powered curriculum design.
        </p>

        <Row className="mb-5">
          <Col md={6}>
            <Card className="p-4 shadow-sm">
              <h4>📝 Create Learning Paths</h4>
              <p>Design customized learning materials in minutes.</p>
              <Button variant="primary" onClick={() => navigate("/create")}>
                Start Creating
              </Button>
            </Card>
          </Col>
          <Col md={6}>
            <Card className="p-4 shadow-sm">
              <h4>📚 Explore Courses</h4>
              <p>Browse learning paths generated by the community.</p>
              <Button variant="outline-secondary" onClick={() => navigate("/courses")}>
                Browse Courses
              </Button>
            </Card>
          </Col>
        </Row>

        <h3 className="mb-4">How to Use LearnHub</h3>
        <Row className="mb-5 text-start justify-content-center">
          <Col md={8}>
            <ol>
              <li><strong>Choose Your Topic:</strong> Select a subject and provide a brief description.</li>
              <li><strong>Customize Settings:</strong> Set your preferred difficulty, style, and chapters.</li>
              <li><strong>Generate Learning Path:</strong> AI creates your curriculum.</li>
              <li><strong>Explore and Study:</strong> Access notes, videos, and more.</li>
            </ol>
          </Col>
        </Row>

        <Row>
          <Col md={4}>
            <Card className="p-3">
              <h5>⭐ Quality Content</h5>
              <p>AI-generated learning paths with structured curriculum and best practices.</p>
            </Card>
          </Col>
          <Col md={4}>
            <Card className="p-3">
              <h5>✅ Comprehensive</h5>
              <p>Includes objectives, key concepts, applications, and resources.</p>
            </Card>
          </Col>
          <Col md={4}>
            <Card className="p-3">
              <h5>👥 Community Sharing</h5>
              <p>Browse and learn from paths shared by others.</p>
            </Card>
          </Col>
        </Row>
      </Container>
    </MainLayout>
  );
}
